// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNUnitWeb.Data;

#nullable disable

namespace MyNUnitWeb.Migrations
{
    [DbContext(typeof(TestRunDbContext))]
    [Migration("20250317180454_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MyNUnitWeb.Data.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("MyNUnitWeb.Data.TestRunResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfCancelledTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfFailedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfIgnoredTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPassedTests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfTests")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalDuration")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TestRunResults");
                });
#pragma warning restore 612, 618
        }
    }
}
